/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TFED22ObjectPageObjectPage journey");

        opaTest("Navigate to ZC_TFED22ObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZC_TFED22List.onFilterBar().iExecuteSearch();

            Then.onTheZC_TFED22List.onTable().iCheckRows();
            When.onTheZC_TFED22List.onTable().iPressRow(0);

            Then.onTheZC_TFED22ObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_TFED22ObjectPage.iCheckSection({ section: "idIdentification" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "CarrierID" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "ConnectionID" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "FlightDate" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "Price" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "CurrencyCode" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "PlaneTypeID" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "SeatsMax" });
            Then.onTheZC_TFED22ObjectPage.onForm({ section: "idIdentification" }).iCheckField({ property: "SeatsOccupied" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});