/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_TFED22ListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_TFED22List.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_TFED22List.onFilterBar().iCheckFilterField("Flight Date");
            Then.onTheZC_TFED22List.onFilterBar().iCheckFilterField("Connection Number");
            Then.onTheZC_TFED22List.onFilterBar().iCheckFilterField("Airline");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_TFED22List.onTable().iCheckColumns(undefined, {"CarrierID":{"header":"Airline"},"ConnectionID":{"header":"Connection Number"},"FlightDate":{"header":"Flight Date"},"Price":{"header":"Airfare"},"CurrencyCode":{"header":"Airline Currency"},"PlaneTypeID":{"header":"Plane Type"},"SeatsMax":{"header":"Max. Capacity Econ."},"SeatsOccupied":{"header":"Occupied Econ."},"LastChangedAt":{"header":"Changed On"},"LastChangedBy":{"header":"Changed By"},"CreatedAt":{"header":"Created On"},"CreatedBy":{"header":"Created By"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_TFED22List.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_TFED22List.onTable().iCheckRows();

            When.onTheZC_TFED22List.onTable().iPressRow(0);
            Then.onTheZC_TFED22ObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});